#!/bin/sh

output="/upstream.conf"
test "$NODE_PORT" || NODE_PORT=3000
set -ue

echo "ENV:"
env
echo "---"
echo " "

echo "# auto-generated by startup.sh" | tee $output
echo "upstream bootstrapcdn {" | tee -a $output
for ip in $(env | grep "${NODE_PORT}_TCP=" | awk -F'=tcp://' '{print $NF}' | sort -u); do
  echo "    server $ip max_fails=3 fail_timeout=10s;" | tee -a $output
done

echo "}" | tee -a $output

exec nginx -c /nginx.conf -g 'daemon off;'
